smallrye/smallrye-mutiny

CONTRIBUTING.md
dco.txt
documentation/src/main/docs/docinfo.html
documentation/src/main/docs/faq.adoc
documentation/src/main/docs/getting-started.adoc
documentation/src/test/java/snippets/GettingStarted.java
documentation/src/test/java/snippets/ThenTest.java

This PR:
1. Adds the github ribbon in the doc
2. Fix a few asciidoctor issues in the documentation
3. Add the contribution guide

Contribution guide and ribbon

---

implementation/src/main/java/io/smallrye/mutiny/Uni.java

refactor: avoid raw UniOr

---

documentation/src/main/docs/faq.adoc
documentation/src/main/docs/getting-started.adoc
documentation/src/main/docs/philosophy.adoc

docs: minor documentation fixes

---

.build/deploy.sh
.build/post-release.kts
.build/pre-release.kts
.build/script.kts
.github/workflows/deployment.yml
.github/workflows/test-script.yaml

* micro release management
* milestone, release, issue checks
* prerequisites and post-actions

Automate release process

---

documentation/src/main/docs/faq.adoc
documentation/src/test/java/snippets/PaginationTest.java
documentation/src/test/java/snippets/PollableSourceTest.java
implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreateBy.java
implementation/src/main/java/io/smallrye/mutiny/groups/MultiRepetition.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniCreateFromCompletionStage.java
implementation/src/test/java/io/smallrye/mutiny/groups/MultiRepetitionTest.java
implementation/src/test/java/tck/MultiRepeatTckTest.java

This is the same feature as Uni.repeat but created from Multi directly.

Add Multi.repeating

---

implementation/src/main/java/io/smallrye/mutiny/groups/MultiRetry.java
implementation/src/main/java/io/smallrye/mutiny/helpers/ExponentialBackoff.java
implementation/src/main/java/io/smallrye/mutiny/helpers/Subscriptions.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRetryOp.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRetryWhenOp.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/processors/DirectProcessor.java
implementation/src/test/java/io/smallrye/mutiny/groups/MultiFlattenTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryWhenTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/multi/processors/DirectProcessorTest.java

For the record; it does not address Uni, Uni is tracked by https://github.com/smallrye/smallrye-mutiny/issues/79.

Add support for retry back-off in Multi

---

pom.xml

It would be nice to have Dependabot configured in this repo :wink:

Bump smallrye-config to 1.7.0

---

documentation/src/main/docs/faq.adoc
documentation/src/test/java/snippets/UniBlockingTest.java

Add a few sentences and an example illustrating how to invoke a blocking method for each item of a Multi.
Fix https://github.com/smallrye/smallrye-mutiny/issues/84.

Explain the difference between emitOn and subscribeOn

---

documentation/src/main/docs/faq.adoc
documentation/src/test/java/snippets/BroadcastProcessorTest.java
implementation/src/main/java/io/smallrye/mutiny/helpers/Subscriptions.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/processors/BroadcastProcessor.java
implementation/src/test/java/io/smallrye/mutiny/operators/multi/processors/BroadcastProcessorTest.java

Add support for hot streams using a BroadcastProcessor

---

.github/workflows/build-master.yml
.github/workflows/build-pull.yml

Enable java 14 build

---

documentation/src/main/docs/faq.adoc
documentation/src/test/java/snippets/EmitterTest.java
implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java

add documentation about emitter and mention hot stream creation

---

documentation/src/main/docs/faq.adoc
documentation/src/test/java/snippets/HowToJoinAsyncTest.java

#108 
Multi was already documentation, but not Uni. This PR adds the documentation for Uni.

Document Uni combination

---

documentation/src/main/docs/faq.adoc
documentation/src/test/java/snippets/DelayTest.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnResultDelay.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniDelayUntil.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemDelayUntilTest.java

Implement Uni.onItem().delayIt().until()

---

implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSignalConsumerOp.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java

If the Multi sends a terminal events and the user cancels, the termination callback must not be called twice (only the first event should call it).
Also fix the failure propagation when onTermination throws exceptions

onTermination must be called only once

---

implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromEmitterTest.java

Add some test verifying that emitter can have multiple subscribers

---

implementation/src/main/java/io/smallrye/mutiny/Uni.java
implementation/src/main/java/io/smallrye/mutiny/groups/MultiItemCombination.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup6.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup7.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup8.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup9.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniZip.java
implementation/src/main/java/io/smallrye/mutiny/operators/MultiItemCombine3.java
implementation/src/main/java/io/smallrye/mutiny/operators/MultiItemCombine5.java
implementation/src/main/java/io/smallrye/mutiny/operators/MultiItemCombine6.java
implementation/src/main/java/io/smallrye/mutiny/operators/MultiItemCombine7.java
implementation/src/main/java/io/smallrye/mutiny/operators/MultiItemCombine8.java
implementation/src/main/java/io/smallrye/mutiny/operators/MultiItemCombine9.java
implementation/src/main/java/io/smallrye/mutiny/tuples/Functions.java
implementation/src/main/java/io/smallrye/mutiny/tuples/Tuple5.java
implementation/src/main/java/io/smallrye/mutiny/tuples/Tuple6.java
implementation/src/main/java/io/smallrye/mutiny/tuples/Tuple7.java
implementation/src/main/java/io/smallrye/mutiny/tuples/Tuple8.java
implementation/src/main/java/io/smallrye/mutiny/tuples/Tuple9.java
implementation/src/main/java/io/smallrye/mutiny/tuples/Tuples.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiCombineTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniAndTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniZipTest.java
implementation/src/test/java/io/smallrye/mutiny/tuples/FunctionsTest.java
implementation/src/test/java/io/smallrye/mutiny/tuples/Tuple6Test.java
implementation/src/test/java/io/smallrye/mutiny/tuples/Tuple7Test.java
implementation/src/test/java/io/smallrye/mutiny/tuples/Tuple8Test.java
implementation/src/test/java/io/smallrye/mutiny/tuples/Tuple9Test.java

This PR adds support for Tuple 7 to 9 and add the corresponding operators (as well as the tests)

Add support for Tuple7 to 9

---

implementation/src/main/java/io/smallrye/mutiny/Uni.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailure.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailureRetry.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItem.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItemOrFailure.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnResultDelay.java
implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniFlatMapCompletionStageOnItem.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniOnFailureFlatMap.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniOnFailureMap.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemConsume.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemFlatMap.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemMap.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemOrFailureConsume.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemOrFailureFlatMap.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemOrFailureMap.java
implementation/src/test/java/io/smallrye/mutiny/groups/UniOnFailureRetryTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureMapToTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemMapTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureFlatMapTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureInvokeTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureMapTest.java

This group allows handling both item and failure in one "go".

Add Uni.onItemOrFailure group

---

implementation/src/main/java/io/smallrye/mutiny/helpers/HalfSerializer.java
implementation/src/main/java/io/smallrye/mutiny/helpers/StrictMultiSubscriber.java
implementation/src/main/java/io/smallrye/mutiny/helpers/Subscriptions.java
implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniProduceMultiOnItem.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFlatMapOp.java
implementation/src/main/java/io/smallrye/mutiny/subscription/SafeSubscriber.java
implementation/src/test/java/io/smallrye/mutiny/helpers/HalfSerializerTest.java
implementation/src/test/java/io/smallrye/mutiny/helpers/StrictMultiSubscriberTest.java
implementation/src/test/java/io/smallrye/mutiny/helpers/SubscriptionsTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryWhenTest.java
implementation/src/test/java/tck/AbstractPublisherTck.java
reactive-streams-operators/pom.xml
reactive-streams-operators/src/main/java/io/smallrye/mutiny/streams/utils/ConnectableProcessor.java
reactive-streams-operators/src/main/java/io/smallrye/mutiny/streams/utils/CouplingProcessor.java
reactive-streams-operators/src/main/java/io/smallrye/mutiny/streams/utils/WrappedProcessor.java
reactive-streams-operators/src/main/java/io/smallrye/mutiny/streams/utils/WrappedSubscriber.java
reactive-streams-operators/src/test/java/tck/ReactiveStreamsEngineImplTck.java

Enable the Reactive Streams Operators TCK

---

implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFlatMapOp.java
implementation/src/main/java/io/smallrye/mutiny/subscription/SafeSubscriber.java
implementation/src/test/java/io/smallrye/mutiny/subscription/SafeSubscriberTest.java

* Ensure protocol violations
* Fix NPE in MultiFlatMap operator when cancellation happens without a subscription

Improve safe subscriber

---

implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnFailure.java
implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailure.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItem.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItemIgnore.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItemOrFailure.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnNotNull.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemFlatMap.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureInvokeUniTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureInvokeTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureRecoveryTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemInvokeTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureInvokeTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnNotNullItemTest.java
implementation/src/test/java/tck/MultiOnFailureInvokeTckTest.java
implementation/src/test/java/tck/MultiOnFailureInvokeUniTckTest.java
implementation/src/test/java/tck/MultiOnItemInvokeTckTest.java
implementation/src/test/java/tck/MultiOnItemInvokeUniTckTest.java

Add `onItem() / onFailure() invokeUni`.	
Relates to #178.

Add onItem() / onFailure() invokeUni

---

implementation/src/main/java/io/smallrye/mutiny/Uni.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniAndTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOrTest.java

Deprecate Uni.and / Uni.or

---

implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromTimePeriodTest.java

Improve flaky tests in io.smallrye.mutiny.operators.MultiCreateFromTimePeriodTest﻿

Improve flaky tests in io.smallrye.mutiny.operators.MultiCreateFromTimePeriodTest

---

documentation/src/main/docs/faq.adoc
implementation/src/main/java/io/smallrye/mutiny/Uni.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java

This is the equivalent of a finally block in Java.
Relates to #178

Add eventually methods to Uni

---

implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnSubscribeInvokeUniOp.java

They should have been removed before.

Remove traces from the MultiOnSubscribeInvokeUniOp

---

implementation/src/main/java/io/smallrye/mutiny/Multi.java
implementation/src/main/java/io/smallrye/mutiny/Uni.java
implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnTerminate.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnEvent.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnTerminate.java
implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniOnTerminationInvokeUni.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnTerminationInvoke.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnTerminationInvokeUni.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnTerminationUniInvokeTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
implementation/src/test/java/tck/MultiCollectTest.java
implementation/src/test/java/tck/MultiDistinctTckTest.java
implementation/src/test/java/tck/MultiFirstTckTest.java
implementation/src/test/java/tck/MultiFlatMapCompletionStageTckTest.java
implementation/src/test/java/tck/MultiFlatMapTckTest.java
implementation/src/test/java/tck/MultiMapTckTest.java
implementation/src/test/java/tck/MultiOnTerminationInvokeTckTest.java
implementation/src/test/java/tck/MultiOnTerminationInvokeUniTckTest.java
implementation/src/test/java/tck/MultiSkipItemsWhileTckTest.java
implementation/src/test/java/tck/MultiTakeFirstItemsTckTest.java
implementation/src/test/java/tck/MultiTakeItemsWhileTckTest.java
reactive-streams-operators/src/main/java/io/smallrye/mutiny/streams/stages/ConcatStageFactory.java
reactive-streams-operators/src/main/java/io/smallrye/mutiny/streams/stages/OnTerminateStageFactory.java

Proposal for https://github.com/smallrye/smallrye-mutiny/issues/159

Move onTermination to its own group

---

documentation/src/test/java/snippets/EventsTest.java
implementation/src/main/java/io/smallrye/mutiny/Multi.java
implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnRequest.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnEvent.java
implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnRequestInvoke.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnRequestInvokeUni.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnRequestTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnTerminationUniInvokeTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
implementation/src/test/java/tck/MultiOnRequestInvokeTckTest.java
implementation/src/test/java/tck/MultiOnRequestInvokeUniTckTest.java

See #230 
Also introduces a group for `Multi.onRequest()`.

Harmonize group access

---

implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToUniTest.java

Increase test coverage in MultiTransformToUniTest

---

documentation/src/main/docs/faq.adoc
documentation/src/test/java/snippets/DroppedExceptionTest.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniSubscribe.java
implementation/src/main/java/io/smallrye/mutiny/helpers/UniCallbackSubscriber.java
implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniOnCancellationInvokeUni.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniOnTerminationInvokeUni.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnCancellationInvoke.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnTerminationInvoke.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnTerminationInvokeUni.java
implementation/src/test/java/io/smallrye/mutiny/infrastructure/DroppedExceptionsTest.java

Offers an infrastructure hook for handling dropped / swallowed exceptions.
Fixes #252

Infrastructure hook for dropped exceptions

---

pom.xml
rxjava/src/main/java/io/smallrye/mutiny/converters/multi/ToMaybe.java
rxjava/src/main/java/io/smallrye/mutiny/converters/uni/FromMaybe.java
rxjava/src/main/java/io/smallrye/mutiny/converters/uni/ToMaybe.java
rxjava/src/test/java/io/smallrye/mutiny/converters/MultiConvertFromTest.java
rxjava/src/test/java/io/smallrye/mutiny/converters/MultiConvertToTest.java
rxjava/src/test/java/io/smallrye/mutiny/converters/UniConvertFromTest.java
rxjava/src/test/java/io/smallrye/mutiny/converters/UniConvertToTest.java

Fix the RX Maybe converters when handling cancellation.﻿

Fix RX Maybe converters when handling cancellation

---

documentation/src/main/docs/faq.adoc
implementation/src/main/java/io/smallrye/mutiny/helpers/BlockingIterable.java
implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
implementation/src/main/java/io/smallrye/mutiny/operators/UniBlockingAwait.java
implementation/src/test/java/io/smallrye/mutiny/helpers/BlockingIterableTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniAwaitTest.java

Infrastructure hook to check the caller thread on blocking operations

---

implementation/pom.xml
implementation/src/main/module/module-info.java
pom.xml

Use Moditect to generate package-info for the main Mutiny module

---

documentation/src/main/docs/philosophy.adoc
documentation/src/test/java/snippets/HowToJoinAsyncTest.java
documentation/src/test/java/snippets/StageTest.java
documentation/src/test/java/snippets/UniMultiComparisonTest.java
implementation/src/main/java/io/smallrye/mutiny/Multi.java
implementation/src/main/java/io/smallrye/mutiny/Uni.java
implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnEvent.java

Deprecate `MultiOnEvent` and `UniOnEvent`, see #286

Deprecate MultiOnEvent and UniOnEvent

---

implementation/src/main/java/io/smallrye/mutiny/Uni.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniReplaceWithTest.java

New Uni.replaceWith shortcuts

---

implementation/src/main/java/io/smallrye/mutiny/Uni.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailure.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureRecoveryTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniReplaceWithTest.java

Uni.replaceWithNull and UniOnFailure.recoverWithNull

---

implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToMultiTest.java

Verify downstream emission when merged or cancatenated inners are emitting from various threads.﻿

Add tests verifying the correctness of inner merge and concat when the emission are done on different threads

---

implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureInvokeTest.java

There is a sporadic failure in CI with a ConditionTimeout in `await().until(called::get)`.

Alternate testCancellationBeforeActionCompletes

---

implementation/src/main/java/io/smallrye/mutiny/groups/MultiGroupIntoLists.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiGroupTest.java

Fixes #232. Thanks to @dcram for providing the code idea.

Implement batching with maximumDelay

---

implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java

Clarify what happens when the supplier is null

---

implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromPublisherTest.java

The new `Multi.createFrom().safePublisher(publisher)` method creates a `Multi`
without going through a `SafeSubscriber`, which reduces the overhead for
publishers that are fully Reactive Streams compliant.
The behavior of `Multi.createFrom().publisher(publisher)` is still to assume
that a publisher may do something wrong, hence `SafeSubscriber` ensures protocol
correctness and reports any mistake.

Allow Multi creation from publishers that are assumed to be TCK-compliant

---

.build/deploy-site.sh
.build/deploy.sh
.github/workflows/deployment.yml

The tentative release of Mutiny 0.12.0 failed due to `bundle` not being available.

Fix the website deployment

---

implementation/revapi.json
implementation/src/main/java/io/smallrye/mutiny/helpers/test/AbstractSubscriber.java
implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertionHelper.java
implementation/src/main/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriber.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/EmitterBasedMulti.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/SerializedMultiEmitter.java
implementation/src/test/java/io/smallrye/mutiny/groups/MultiBroadcastTest.java
implementation/src/test/java/io/smallrye/mutiny/helpers/test/AbstractSubscriberTest.java
implementation/src/test/java/io/smallrye/mutiny/helpers/test/AssertSubscriberTest.java
implementation/src/test/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriberTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToMultiTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/EmitterBasedMultiTest.java

Improve the test utilities
- Rework the test assertions
- Remove the spy subscribers
- Refactor the multi emitters

Improve test utilities

---

implementation/src/main/module/module-info.java

﻿Fix https://github.com/smallrye/smallrye-mutiny/issues/411

Add helpers.{spies,test} and subscription packages in the module-info.java

---

implementation/src/main/java/io/smallrye/mutiny/groups/MultiCollect.java
implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiCollectTest.java

Add multi.collect().where(...) and multi.collect().when(...)﻿

Add multi.collect().where(...) and multi.collect().when(...).

---

implementation/revapi.json
implementation/src/main/java/io/smallrye/mutiny/operators/multi/AbstractMultiOperator.java
implementation/src/test/java/io/smallrye/mutiny/operators/multi/AbstractMultiOperatorTest.java
pom.xml
reactor/revapi.json
rxjava/revapi.json

To:
```xml
<revapi-maven-plugin.version>0.13.0</revapi-maven-plugin.version>
<revapi-java.version>0.23.0</revapi-java.version>
<revapi-reporter-json.version>0.3.0</revapi-reporter-json.version>
<revapi-reporter-text.version>0.13.0</revapi-reporter-text.version>
```
Supersedes #427 
Supersedes #426 
Supersedes #425
Supersedes #424

Bump revapi versions

---

documentation/pom.xml
documentation/src/main/jekyll/_data/categories.yml
documentation/src/main/jekyll/_data/guides.yml
documentation/src/main/jekyll/guides/kotlin.adoc
documentation/src/test/kotlin/guides/Coroutines.kt
kotlin/pom.xml
kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Multi.kt
kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Uni.kt
kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Util.kt
kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/DeferredAsUniTest.kt
kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/FlowAsMultiTest.kt
kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/MultiAsFlowTest.kt
kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/UniAwaitSuspendingTest.kt
pom.xml

Solves https://github.com/smallrye/smallrye-mutiny/issues/403
Tasks:

Kotlin module

---

pom.xml

Update revapi to:
```xml
﻿        <revapi-maven-plugin.version>0.13.1</revapi-maven-plugin.version>
<revapi-java.version>0.23.1</revapi-java.version>
<revapi-reporter-json.version>0.3.1</revapi-reporter-json.version>
<revapi-reporter-text.version>0.13.1</revapi-reporter-text.version>
```
Replace #430, #431, #432 and #434

Update RevAPI 

---

context-propagation/pom.xml
documentation/pom.xml
implementation/pom.xml
kotlin/pom.xml
pom.xml
reactive-streams-junit5-tck/pom.xml
reactive-streams-operators/pom.xml
reactor/pom.xml
release/pom.xml
rxjava/pom.xml
test-utils/pom.xml

Align name and descriptions (when present)

Maven POM descriptors cosmetics

---

pom.xml

```xml
<revapi-maven-plugin.version>0.13.2</revapi-maven-plugin.version>
<revapi-java.version>0.23.2</revapi-java.version>
<revapi-reporter-json.version>0.3.2</revapi-reporter-json.version>
<revapi-reporter-text.version>0.13.2</revapi-reporter-text.version>
```
Replacing #437 #436 #438 and #439

Another RevAPI update

---

implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java
implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromFuture.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniCreateFromFutureTest.java

Add the ability to create a Uni from a Future or a Supplier of Future

---

implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/IntervalMulti.java

Cancel the submitted tasks to avoid useless executions.

Explicitly cancel the scheduled future upon user's cancellation

---

documentation/src/main/jekyll/_layouts/index.html
documentation/src/main/jekyll/pages/philosophy.adoc
documentation/src/test/java/guides/EventsTest.java

I noticed a few typos while reading the doc. Here's a proposal to fix them.

Fix doc typos

---

implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/BaseMultiEmitter.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/BufferItemMultiEmitter.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/EmitterBasedMulti.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromEmitterTest.java

Implement Multi.createFrom().emitter(Consumer, int buffSize)

---

kotlin/pom.xml
pom.xml

Remove JCenter

---

implementation/src/main/java/io/smallrye/mutiny/groups/UniZip.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniZipTest.java

Enforce API contract on UniCombine emptiness

---

documentation/src/main/jekyll/guides/shortcuts.adoc
implementation/src/main/java/io/smallrye/mutiny/Uni.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniReplaceWithTest.java

Implement Uni.replaceIfNullWith(value / supplier) shortcuts

---

implementation/src/main/java/io/smallrye/mutiny/groups/UniOnNotNull.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnNotNullItemTest.java

Add the following sintax
```
Uni.createFrom().item("hello").onItem().ifNotNull().failWith(() ->  new IllegalStateException("boom"))
```
Fixes #624 
Need a little help to check typos, english is not my main language! 😞

Add failWith methods to UniOnNotNull

---

documentation/src/main/jekyll/getting-started/observing-events.adoc

Hi Congrats on a great library!
I started reading the docs and noticed a couple very small typos.
Anyway thanks for such an awesome project!

Random type fixes

---

documentation/pom.xml
pom.xml

Grouped RevAPI + Logback upgrades

Grouped dependencies updates

---

implementation/revapi.json
implementation/src/main/java/io/smallrye/mutiny/Multi.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniJoin.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFailOnItemTimeout.java
implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinAll.java
implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinFirst.java
implementation/src/test/java/io/smallrye/mutiny/BugReproducersTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/uni/UniJoinTest.java
implementation/src/test/java/io/smallrye/mutiny/subscription/SerializedSubscriberTest.java
implementation/src/test/java/io/smallrye/mutiny/unchecked/UncheckedConsumerTest.java

Fixes https://github.com/quarkusio/quarkus/issues/21528

Fix and simplify Uni.join() parametric types

---

kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Uni.kt
kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/DeferredAsUniTest.kt

This is an attempt to resolve #752

test(kotlin): create test to cancel deferred

---

kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Multi.kt
kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/FlowAsMultiTest.kt

This ensures that cancellation of a `Multi` produced from using `Flow.asMulti` will properly cancel the flow.
This works by cancelling the job that is executing that `Flow.collect`; which is the proper way of cancelling a flow collection. Importantly this works with complex flow types like `callbackFlow`.

Properly propagate `Multi` cancellation to `Flow` when using `Flow.asMulti`

---

.build/CompatibilityUtils.java

Fixes https://github.com/smallrye/smallrye-mutiny/issues/804

Improve breaking changes presentation

---

implementation/revapi.json
implementation/src/main/java/io/smallrye/mutiny/groups/MultiRetry.java
implementation/src/main/java/io/smallrye/mutiny/groups/UniRetry.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRetryOp.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRetryWhenOp.java
implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniRetryAtMost.java
implementation/src/test/java/io/smallrye/mutiny/groups/UniOnFailureRetryTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryUntilTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryWhenTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureRetryUntilTest.java

MultiOnRetry is ignoring the onFailure predicate

---

.build/CompatibilityUtils.java

See https://github.com/smallrye/smallrye-mutiny/issues/767

Add the ability not to clear certain versions

---

documentation/src/main/jekyll/_data/categories.yml
documentation/src/main/jekyll/_data/guides.yml
documentation/src/main/jekyll/guides/replaying-multis.adoc
documentation/src/test/java/guides/operators/ReplayTest.java
implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreateBy.java
implementation/src/main/java/io/smallrye/mutiny/groups/MultiReplay.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/replay/AppendOnlyReplayList.java
implementation/src/main/java/io/smallrye/mutiny/operators/multi/replay/ReplayOperator.java
implementation/src/test/java/io/smallrye/mutiny/groups/MultiReplayTest.java
implementation/src/test/java/io/smallrye/mutiny/operators/multi/replay/AppendOnlyReplayListTest.java
pom.xml
reactive-streams-tck-tests/src/test/java/io/smallrye/mutiny/tcktests/MultiReplayTckTest.java

Replay a Multi (turned into a hot stream) to multiple (possibly late) subscribers.
See https://github.com/smallrye/smallrye-mutiny/issues/536 for the initial discussion.

Multi replay operator (experimental API)

---

implementation/revapi.json
implementation/src/main/java/io/smallrye/mutiny/helpers/spies/Spy.java

Promote spies to a stable API

---

implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java
implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromFuture.java
implementation/src/test/java/io/smallrye/mutiny/operators/UniCreateFromFutureTest.java

In some cases it is impossible to control passed future object and the executor thread may be blocked forever, so i think that timeout can be useful to avoid it and at least fail with `TimeoutException` 🙂

Allow to set timeout in UniCreate.future

---

.github/workflows/build-1.x.yml
.github/workflows/build-main.yml
.github/workflows/build-pull.yml
.github/workflows/post-release.yml

I also added a refinement to the concurrency management (looks like some concurrent PRs could cancel each other).
Fixes #848
Uses #861

CI configuration for 2.0 / 1.x branches

---

.build/CompatibilityUtils.java
.github/workflows/deploy-site.yml

- Do not clear compatibility justifications on known pre-release patterns
- Only deploy the website for final (x.y.z) releases

Allow for pre-releases deployment

---

pom.xml

Reverts smallrye/smallrye-mutiny#1021

Revert "Bump testng from 7.5 to 7.6.1"

---

.github/workflows/build-pull-1.x.yml

I deliberately chose to duplicate and simplify the main PR check workflow instead of looking for conditionals and exclusions in matrix.

Check pull-requests against the 1.x branch

---

documentation/docs/guides/spies.md
documentation/mkdocs.yml
documentation/src/test/java/guides/SpiesTest.java

Document the usage of spies (advanced guide)

---

pom.xml
reactive-streams-operators-jakarta/pom.xml

Update the implementation of Reactive Streams Operators from the 1.x branch

Update the Reactive Streams Operators 3.x implementation (jakarta)

---

kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Multi.kt
kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/MultiAsFlowTest.kt

see https://github.com/smallrye/smallrye-mutiny/pull/1104

#1103 Refactor Multi.toFlow() to avoid blocking - Mutiny2

---

implementation/src/main/java/io/smallrye/mutiny/operators/multi/processors/UnicastProcessor.java

Document that UnicastProcessor cannot be re-subscribed

---

documentation/docs/guides/merging-and-concatenating-streams.md

Remove extra `onItem(1)` in documentation

---

.github/workflows/build-main.yml

Grouped the compatibility and code coverage steps, reduce build times.

Simplify QA steps in the main branch workflow

---

documentation/docs/guides/shortcut-methods.md
documentation/src/main/jekyll/guides/shortcuts.adoc
implementation/src/main/java/io/smallrye/mutiny/Uni.java

cherry picked from commit 22d63005c2c58183c32497dcc022fd4e6193fcd8

Remove then from the shortcut list and from the javadoc

---

README.md
pom.xml

Quick Maven build profile

---

documentation/docs/tutorials/transforming-items-asynchronously.md

Documentation: insist on merging vs concatenating order semantics

---

implementation/src/main/java/io/smallrye/mutiny/groups/UniMemoize.java
implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java

Rename UniMemoize#atLeast to forFixedDuration

---

implementation/src/main/java/io/smallrye/mutiny/groups/UniRepeat.java

Fix description of the UniRepeat::whilst method

---

pom.xml

- Detect milestones and mark them as pre-releases
- Tentative: announce in GitHub Discussions

JReleaser refinements

---

documentation/docs/guides/broadcasting-to-multiple-subscribers.md
documentation/mkdocs.yml

docs: document the broadcast operator

---

implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiConcatMapOp.java
implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiConcatMapNoPrefetchTest.java

This fixes the NPE #1498 and reveals a deadlock problem.

fix: concatMap early first upstream issues

---

implementation/revapi.json
implementation/src/main/java/io/smallrye/mutiny/Multi.java

This has been successfully used in SmallRye Reactive Messaging / Quarkus.

feat: promotion of the experimental Multi splitter API

---

implementation/src/main/java/io/smallrye/mutiny/operators/multi/processors/BroadcastProcessor.java

Refs: #1532
(cherry picked from commit 6a2c6f0275bd9ba3aa04014fb66b25ccf1f9c437)

fix(BroadcastProcessor): prevent memory leaks by clearing active subscriptions

---

workshop-examples/src/main/java/_02_groups/_04_Multi_Event_Groups.java

This is the same as https://github.com/smallrye/smallrye-mutiny/pull/1556 using a conventional commit message

fix(workshop): Variable wasn't printed

---

reactive-streams-tck-tests/src/test/java/io/smallrye/mutiny/tcktests/MultiConcatMapNoPrefetchCompletionStageTckTest.java

test: skip stochastic tests in MultiConcatMapNoPrefetchCompletionStageTckTest

---

.github/workflows/pre-release.yml
justfile

- **build: introduce a justfile**
- **ci: meta-data and branch preparation will now be run locally using just**

Run local tasks ahead of preparing a release

---

pom.xml

Supersedes #1862 #1861 #1860 #1859

build(deps): coordinated RevAPI bumps to 0.28.3
