smallrye/smallrye-mutiny

- documentation/src/test/java/snippets/UniTimeoutTest.java
- implementation/src/main/java/io/smallrye/mutiny/Uni.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniIfNoItem.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniIfNoItemTest.java
Fix #28 
Introduce an intermediary group to avoid using recovery methods without timeout.
> Fix #28 - It should not be possible to not set the timeout

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/StreamBasedMulti.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/processors/UnicastProcessor.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromItemsTest.java
- implementation/src/test/java/tck/MultiFromStreamTckTest.java
The previous implementation was eager and relied on calling forEach. It was not handling infinite stream.
This version does and also add support for the close callback.
> Provide an implementation of Multi consuming a java.util.Stream in a lazy fashion

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnEvent.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
- implementation/src/test/java/tck/MultiCollectTest.java
- implementation/src/test/java/tck/MultiDistinctTckTest.java
- implementation/src/test/java/tck/MultiFirstTckTest.java
- implementation/src/test/java/tck/MultiFlatMapCompletionStageTckTest.java
- implementation/src/test/java/tck/MultiFlatMapTckTest.java
- implementation/src/test/java/tck/MultiMapTckTest.java
- implementation/src/test/java/tck/MultiSkipItemsWhileTckTest.java
- implementation/src/test/java/tck/MultiTakeFirstItemsTckTest.java
- implementation/src/test/java/tck/MultiTakeItemsWhileTckTest.java
- reactive-streams-operators/src/main/java/io/smallrye/mutiny/streams/stages/ConcatStageFactory.java
- reactive-streams-operators/src/main/java/io/smallrye/mutiny/streams/stages/OnTerminateStageFactory.java
* Align the `subscribed` event name between Uni and Multi
* Provides `on().termination(...)` variant ignoring the event details (just getting a `Runnable`)
> Improvements around event handlers

- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
Definitely a bug, all new instances of Uni must call the `onUniCreation` hook.
> Uni creation in AbstractUni must call the onUniCreation hook

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiIfEmpty.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnNull.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/Predicates.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
- implementation/src/main/java/io/smallrye/mutiny/operators/MultiSwitchOnCompletion.java
- implementation/src/main/java/io/smallrye/mutiny/operators/MultiSwitchOnEmpty.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniAndCombination.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniCallSubscribeOn.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniCreateFromCompletionStage.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniCreateFromDeferredSupplier.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniFailOnTimeout.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniFlatMapCompletionStageOnItem.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniFlatMapOnItem.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniMapOnFailure.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniMapOnResult.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniOnSubscription.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniOnTermination.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiCollectorOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiWindowOnDurationOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/BufferItemMultiEmitter.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/FailedMulti.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/StreamBasedMulti.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnResultMapToItem.java
The user code may throw other types of throwable and it needs to be propagated downstream.
Typically, in a test, the user may use assertions that would throw AssertionError. This should be propagated downstream.
> Catch Throwable instead of Exception

- implementation/src/main/java/io/smallrye/mutiny/helpers/MultiEmitterProcessor.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/BaseMultiEmitter.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/SerializedMultiEmitter.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/MultiEmitter.java
- implementation/src/test/java/io/smallrye/mutiny/groups/MultiBroadcastTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromEmitterTest.java
These methods are required to implement the Reactive Messaging Emitter interface (same name, not the same purpose).
> Add requested and isCancelled method to the MultiEmitter.

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiCollectorOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiCollectTest.java
In this case, `null` should be ignored and the stream completed.
> Collector finisher can return `null`

- context-propagation/src/test/java/io/smallrye/mutiny/context/MultiContextPropagationTest.java
- context-propagation/src/test/java/io/smallrye/mutiny/context/UniContextPropagationTest.java
- documentation/src/main/docs/faq.adoc
- documentation/src/main/docs/plantuml/emitOn-sequence.puml
- documentation/src/main/docs/plantuml/runSubscriptionOn-sequence.puml
- documentation/src/test/java/snippets/PollableSourceTest.java
- documentation/src/test/java/snippets/RunSubscriptionOnTest.java
- documentation/src/test/java/snippets/UniBlockingTest.java
- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/Uni.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/UniSubscriber.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiReceiveItemOnTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniRepeatTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniRunSubscriptionOnTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromIterableTest.java
Fix #98
Also add a section in the doc clarifying `emitOn` vs. `runSubscriptionOn`
> Rename subscribeOn to runSubscriptionOn

- documentation/src/main/docs/faq.adoc
- documentation/src/test/java/snippets/MergeVsConcatenateTest.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiFlatten.java
- implementation/src/test/java/tck/MultiFlatMapCompletionStageTckTest.java
- implementation/src/test/java/tck/MultiFlatMapTckTest.java
Also fix the default concurrency argument of the merge operation.
Fix #82
> Document the difference between concatenate() and merge()

- documentation/src/main/docs/faq.adoc
- documentation/src/test/java/snippets/HowToTransformTest.java
- implementation/src/main/java/io/smallrye/mutiny/unchecked/Unchecked.java
- implementation/src/main/java/io/smallrye/mutiny/unchecked/UncheckedBiConsumer.java
- implementation/src/main/java/io/smallrye/mutiny/unchecked/UncheckedBiFunction.java
- implementation/src/main/java/io/smallrye/mutiny/unchecked/UncheckedConsumer.java
- implementation/src/main/java/io/smallrye/mutiny/unchecked/UncheckedFunction.java
- implementation/src/main/java/io/smallrye/mutiny/unchecked/UncheckedSupplier.java
- implementation/src/test/java/io/smallrye/mutiny/unchecked/UncheckedBiFunctionTest.java
- implementation/src/test/java/io/smallrye/mutiny/unchecked/UncheckedConsumerTest.java
- implementation/src/test/java/io/smallrye/mutiny/unchecked/UncheckedFunctionTest.java
- implementation/src/test/java/io/smallrye/mutiny/unchecked/UncheckedSupplierTest.java
This PR provides a set of helper classes to ease the integration of operation throwing checked exceptions. `java.util.functions` classes require the code to not throw checked exception. So it can be inconvenient to wrap the code in a try/catch construct. These helpers avoid that by doing the wrapping automatically.
Fix #99.
> Unchecked functions/consumers/suppliers helpers

- documentation/src/main/docs/faq.adoc
- documentation/src/test/java/snippets/UniNullTest.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup2.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItem.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnNotNull.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniZip.java
- implementation/src/main/java/io/smallrye/mutiny/operators/MultiItemCombine2.java
- implementation/src/main/java/io/smallrye/mutiny/operators/MultiItemCombine3.java
- implementation/src/main/java/io/smallrye/mutiny/operators/MultiItemCombine4.java
- implementation/src/main/java/io/smallrye/mutiny/operators/MultiItemCombine5.java
- implementation/src/main/java/io/smallrye/mutiny/operators/MultiItemCombineIterable.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/processors/SerializedProcessor.java
- implementation/src/main/java/io/smallrye/mutiny/unchecked/UncheckedBiFunction.java
- implementation/src/main/java/io/smallrye/mutiny/unchecked/UncheckedConsumer.java
- implementation/src/main/java/io/smallrye/mutiny/unchecked/UncheckedFunction.java
- implementation/src/main/java/io/smallrye/mutiny/unchecked/UncheckedSupplier.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnNotNullItemTest.java
This group checks if the item is not `null`. If the item is `null` default results are provided (`null`, empty `Multi`...)
This PR also contains various cosmetic fixes.
Related to #109
> Implement Uni.onItem().ifNotNull()

- implementation/src/test/java/io/smallrye/mutiny/stack/StackTest.java
Be sure Mutiny is not affected by the deep stack trace issue when reading large buffers
> Add deep stack tests

- documentation/src/test/java/snippets/DelayTest.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroupIterable.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniZipTest.java
This is useful when combining Uni<Void> instances, and even various Unis where we are only interested by the completion of the operation and not the result.
> Add a way to combine Uni and discard the emitted items

- .github/workflows/build-master.yml
- .github/workflows/build-pull.yml
- .github/workflows/deployment.yml
- documentation/pom.xml
* Enable cache - because I'm bored retrying build failing because it cannot download some artifact,
* Remove java 12 - not an LTS,
* Add java 15-ea 
It also uses a matrix build to configure the java version, and update the actions to the latest versions.
The setup-jdk actions have been replaced with the once provided by AdoptOpenJDK (https://github.com/AdoptOpenJDK/install-jdk).
> CI Improvements

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiRetry.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniRetry.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/ExponentialBackoff.java
- implementation/src/test/java/io/smallrye/mutiny/groups/UniOnFailureRetryTest.java
- implementation/src/test/java/io/smallrye/mutiny/infrastructure/MutinySchedulerTest.java
When using exponential back during Uni/Multi retry we must specify a max retry attempts. With these two methods we will be able to specify an expiration time instead.
> Add expireAt/expireIn to back off retry

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniCreateFromCompletionStage.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromCompletionStageTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiFlatMapToPublisherTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniCreateFromCompletionStageTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemFlatMapToCompletionStageTest.java
Fix #179 - Avoid leaking CompletionException when creating a Uni from a CompletionStage﻿
> Avoid leaking CompletionException coming from CompletionStage

- documentation/src/main/docs/faq.adoc
- documentation/src/test/java/snippets/PaginationTest.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniRepeat.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatUntilOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatWhilstOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniRepeatTest.java
- implementation/src/test/java/tck/UniRepeatWhilstTckTest.java
Improve the support of paginated API:
```
Multi<Page> stream = Multi.createBy().repeating()
.uni(
() -> new AtomicInteger(),
state -> api.retrieve(state.getAndIncrement()))
.whilst(page -> page.hasNext());
```
Fix #176
> Add support for repeat whilst

- implementation/src/main/java/io/smallrye/mutiny/CompositeException.java
- implementation/src/test/java/io/smallrye/mutiny/CompositeExceptionTest.java
Improve CompositeException to override getCause (which was null initially).
It also checks that at least one exception is passed.
It might be interested later to use suppressed exceptions.
> Improve CompositeException to override getCause()

- implementation/src/main/java/io/smallrye/mutiny/CompositeException.java
- implementation/src/test/java/io/smallrye/mutiny/CompositeExceptionTest.java
Refactor CompositeException to use suppressed exceptions instead of the explicit list.﻿
> Use suppressed exception instead of explicit list in CompositeException

- implementation/src/main/java/io/smallrye/mutiny/tuples/Functions.java
This is cosmetic but aligns all interfaces since one was already marked with `@FunctionalInterface`.
Fixes #191
> Mark functional interfaces in Functions

- documentation/src/main/docs/faq.adoc
- documentation/src/test/java/snippets/FlatMapTest.java
- implementation/src/main/java/io/smallrye/mutiny/Uni.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformToUniTest.java
- implementation/src/test/java/io/smallrye/mutiny/unchecked/UncheckedFunctionTest.java
Add 2 shortcuts to the `Uni` class:
* `chain`
* `then`
Related to #178.
> Add the Uni.chain and Uni.then shortcuts

- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItem.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemDisjointTest.java
The method was forgotten when the `Multi.onItem().disjoint()` method was added.
> Add Uni.onItem().disjoint() 

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiFlatten.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/Subscriptions.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/queues/EmptyQueue.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/queues/Queues.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/queues/SingletonQueue.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiEmitOnOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFlatMapOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiGroupByOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiWindowOnDurationOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiWindowOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiZipOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/BufferItemMultiEmitter.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/SerializedMultiEmitter.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/multicast/MultiPublishOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/overflow/MultiOnOverflowBufferOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/processors/UnicastProcessor.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/queues/QueuesTest.java
This PR improves the sizing and the kind of the various queues we use.
It creates a central class to create the various type of queues and provide heuristics about the size.
The various operators have been updated to use the right type of queues.
It also fixes #215 as the requests parameter should be used and passed to the operator.
> Optimize Queue usages

- documentation/pom.xml
The update to the asciidoctor-maven-plugin 2.0.0 broke the documentation.
This commit migrates to the new configuration format - see https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/docs/v2-migration-guide.adoc for details.
Two issues were reported:
* The syntax highlighting was not working anymore
* The top image was missing
Once merged I will apply this hotfix on the web site.
> Fix asciidoctor config

- documentation/src/test/java/snippets/EventsTest.java
- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/Uni.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnCancel.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnCancel.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnEvent.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniOnCancellationInvokeUni.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnCancellationInvoke.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnCancellationInvokeUni.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnCancellationInvokeUniTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnTerminationUniInvokeTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformToMultiTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniToMultiTest.java
Fix for #221 
- Move uni.on().cancellation() to uni.onCancellation()
- Move multi.on().cancellation() to multi.onCancellation()
- Documentation update for multi.onCancellation()
> Create onCancellation() groups for Uni and Multi

- implementation/src/main/java/io/smallrye/mutiny/helpers/Caused.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/CausedTest.java
Hello,
I submit this add-on cause I needed it in a project.
I created a Caused class which can be used to fluently unwrap checked exception previously wrapped by Unchecked utilities.
I did it that way so it does not change the onFailure paradigm.
Julien
> Added a Caused.by unwrapper

- context-propagation/pom.xml
- context-propagation/src/main/java/io/smallrye/mutiny/context/ContextPropagationMultiInterceptor.java
- context-propagation/src/test/java/io/smallrye/mutiny/context/MultiContextPropagationTest.java
- context-propagation/src/test/java/io/smallrye/mutiny/context/tck/ContextPropagationMultiTckTest.java
- context-propagation/src/test/java/io/smallrye/mutiny/context/tck/ContextPropagationSubscriberTckTest.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
- reactive-streams-operators/pom.xml
Check for null subscribers in the context propagation implementation of AbstractMulti as mandated by the reactive streams spec.
Also, reduce the number of allocation and delegation as we just need to invoke the `subscribe` method.
> Check for null subscriber in Context Propagation Multi interceptor

- implementation/src/main/java/io/smallrye/mutiny/operators/UniSerializedSubscriber.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniSerializedSubscriberTest.java
Improve the UniSerializerSubscriber
It may not provide a subscription downstream before sending event in some cases.
Add tests verifying the behavior and race conditions.
> Improve the UniSerializedSubscriber

- implementation/src/main/java/io/smallrye/mutiny/operators/UniSerializedSubscriber.java
Fix potential NPE when cancelling the subscription in the UniSerializedSubscriber.﻿
> Fix potential NPE in the UniSerializedSubscriber on cancellation

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOverflow.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiSubscribe.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOr.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/queues/DrainUtils.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/queues/MpscLinkedQueue.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/queues/SpscLinkedArrayQueue.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniRunSubscribeOn.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiBufferWithTimeoutOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiDistinctOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFlatMapOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiMapOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSkipUntilPublisherOp.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/Subscribers.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/queues/DrainUtilsTest.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/queues/QueuesTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiDistinctTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiFilterTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiMergeTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnItemTransformTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiSkipTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToMultiTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureTransformTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniRunSubscriptionOnTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/FlatMapMainSubscriberTest.java
- implementation/src/test/java/tck/MultiOnItemTransformTckTest.java
Several Multi operators where missing tests.
This PR adds some and remove unused code.
- Rename UniOnFailureMApToTest to UniOnFailureTransformTest
- Remove unused constructor
- Verify the behavior of the Distinct Operator
- Improve Multi Skip Until operator and add more tests
- Verify the filter operator upon cancellation and failures/exceptions
- Add more test to Multi flatmap (transformToMulti)
- Add missing @return in MultiOnEvent javadoc
- Remove unused method in MultiBufferWithTimeoutOp
- Add test for the MutlOnItemTransform operator
- Add tests for Queues and make sure all Queue implementations throw UnsupportedOperationExceptions for unsupported operations
- Verify the behavior of the methods from DrainUtils
- Verify failure collection when merging multis
- Removed unused code in …
> Add more tests for some Multi operators

- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/Uni.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnFailure.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiRepetition.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiTransform.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailure.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItem.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItemDelay.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItemOrFailure.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnNotNull.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnTimeout.java
- implementation/src/main/java/io/smallrye/mutiny/operators/MultiFlatMapOnFailure.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniCreateFromDeferredSupplier.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniDelayUntil.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniOnFailureFlatMap.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemOrFailureFlatMap.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemTransformToUni.java
Removes `<? extends Uni>` and `<? extends Multi>` in the API
This does not cover collections and iterables for which this remains useful.
Fixes #265
> Parametric type signatures fixes

- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroupIterable.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAny.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailure.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniZip.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/EmptyUniSubscription.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniOnFailureTransform.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemTransform.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniSerializedSubscriber.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/SafeSubscriber.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/SerializedSubscriber.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/Subscribers.java
- implementation/src/main/java/io/smallrye/mutiny/tuples/Functions.java
- implementation/src/test/java/io/smallrye/mutiny/infrastructure/UniInterceptorTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniAndTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureTransformTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureMapTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniSerializedSubscriberTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniZipTest.java
- implementation/src/test/java/io/smallrye/mutiny/subscription/CallbackBasedSubscriberTest.java
- implementation/src/test/java/io/smallrye/mutiny/subscription/SafeSubscriberTest.java
- implementation/src/test/java/io/smallrye/mutiny/subscription/SerializedSubscriberTest.java
- test-utils/src/main/java/io/smallrye/mutiny/test/AssertSubscriber.java
- Remove guard for concurrent events as the serialized subscriber already takes care of these. Handle dropped exception in the UniSerializedSubscriber
- Add more tests around Uni.combine().all and Uni.combine().any
- Remove unused code and null checks
- Verify ordinal behavior in the UniInterceptor
- Test dropped exception in the SafeSubscriber and CallbackSubscriber
- Fix dropped exception in the SerializedSubscriber and add more tests
> Remove non executed code and continue drop exception integration

- context-propagation/pom.xml
- context-propagation/src/test/java/io/smallrye/mutiny/context/tck/ContextPropagationMultiTckTest.java
- context-propagation/src/test/java/io/smallrye/mutiny/context/tck/ContextPropagationSubscriberTckTest.java
Missed it during the main migration.
Surefire was configured to ignore junit.
> Migrate the context-propagation module to junit 5

- implementation/src/main/java/io/smallrye/mutiny/tuples/Tuple2.java
- implementation/src/test/java/io/smallrye/mutiny/tuples/Tuple2Test.java
- implementation/src/test/java/io/smallrye/mutiny/tuples/Tuple3Test.java
- implementation/src/test/java/io/smallrye/mutiny/tuples/Tuple4Test.java
- implementation/src/test/java/io/smallrye/mutiny/tuples/Tuple5Test.java
- implementation/src/test/java/io/smallrye/mutiny/tuples/Tuple6Test.java
- implementation/src/test/java/io/smallrye/mutiny/tuples/Tuple7Test.java
- implementation/src/test/java/io/smallrye/mutiny/tuples/Tuple8Test.java
- implementation/src/test/java/io/smallrye/mutiny/tuples/Tuple9Test.java
Make sure that Tuple's implementation follow the same toString pattern, and test it.﻿
> Make Tuple's toString homegeneous

- implementation/src/main/java/io/smallrye/mutiny/tuples/Functions.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniIfNoItemTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnTerminationTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniRunSubscriptionOnTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/multicast/MultiReferenceCountSubscriberTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/processors/UnicastProcessorTest.java
- implementation/src/test/java/io/smallrye/mutiny/stack/StackTest.java
Cover multiple areas with tests.
These tests verify edges case like failure management, cancellation... 
It also fixes a few racy tests.
- Verify the behavior of the MultiReferenceCountSubscriber when receiving failures, cancellation and illegal events.
- Add a test using the deprecated Uni.subscribeOn just to verify it's still working
- Fix the UnicastProcessorTest
- Fix test ending with an ArrayOutOfBoundException.
- Verify the behavior of Uni.onTermination when the callback throws exceptions
- Verify Uni Timeout management
> Add more tests to handle edges cases  + Fix racy tests

- .github/workflows/build-master.yml
- .github/workflows/build-pull.yml
The Java 15 build from AdopOnJDK was failing with a certificate issue.
> CI update - Use Ubuntu 20.04 and use Zulu build for Java 15

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnFailure.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiRetry.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniRetry.java
- implementation/src/test/java/io/smallrye/mutiny/groups/UniOnFailureRetryTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryTest.java
Added at UniRetry and MultiRetry the predicate test from the `onFailure()` when using retry with backoff
Closes #301
> UniRetry and MultiRetry now tests the predicate from onFailure() 

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/overflow/MultiOnOverflowBufferOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnOverflowTest.java
Missing upstream cancellation when the backpressure failure is thrown.﻿
> Missing upstream cancellation on back pressure failure

- implementation/src/main/java/io/smallrye/mutiny/operators/UniSerializedSubscriber.java
There is a possibility for cancel to have the subscription become null because an item or a failure is emitted.
This removes the dispose() method whose sole purpose was to set the subscription to null. Since the subscription value being null does not have any value there is no point keeping it around.
> Fix a race condition between onSubscribe / cancel / on{Item,Failure}

- context-propagation/src/main/java/io/smallrye/mutiny/context/ContextPropagationMultiInterceptor.java
- context-propagation/src/main/java/io/smallrye/mutiny/context/ContextPropagationUniInterceptor.java
- context-propagation/src/main/java/io/smallrye/mutiny/context/DefaultContextPropagationMultiInterceptor.java
- context-propagation/src/main/java/io/smallrye/mutiny/context/DefaultContextPropagationUniInterceptor.java
- context-propagation/src/main/resources/META-INF/services/io.smallrye.mutiny.infrastructure.MultiInterceptor
- context-propagation/src/main/resources/META-INF/services/io.smallrye.mutiny.infrastructure.UniInterceptor
- context-propagation/src/test/java/io/smallrye/mutiny/context/tck/ContextPropagationMultiTckTest.java
- context-propagation/src/test/java/io/smallrye/mutiny/context/tck/ContextPropagationSubscriberTckTest.java
In a multi-deployment such as WildFly we need to control which ContextManager is used. I've added some hooks to be able to control that, and provided default implementations of those so that Quarkus can work the way it does. (#335 contains a bit more background why this is needed)
If you want me to rename/move anything let me know.
> Pluggable ThreadContext from the context propagation interceptors

- implementation/src/main/java/io/smallrye/mutiny/infrastructure/ExecutorConfiguration.java
file name is incorrect. ".reactive" is redundant in file name
> Fix mistake in JavaDocs of ExecutorConfiguration

- .build/CompatibilityUtils.java
- .build/deploy.sh
- .build/post-release.kts
- .github/workflows/build-master.yml
- .github/workflows/build-pull.yml
- .github/workflows/deployment.yml
- implementation/pom.xml
- implementation/revapi.json
- implementation/src/main/java/io/smallrye/mutiny/helpers/Subscriptions.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiGroupByOp.java
- pom.xml
- reactor/pom.xml
- reactor/revapi.json
- rxjava/pom.xml
- rxjava/revapi.json
Configure revapi.
Didn't work on the release tooling yet, but should not be hard.
> Initial configuration of revapi to detect API incompatibility.

- implementation/src/main/java/io/smallrye/mutiny/subscription/SafeSubscriber.java
This removes the AtomicReference / volatile semantics out of the way on the hot path,
at the cost of an additional AtomicBoolean to ensure correctness on multiple onSubscribe
signals.
> SafeSubscriber: move the upstream subscription to a regular field

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFilterOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiFilterTest.java
requestedMax doesn't have to be volatile since the subscription check makes for a memory barrier,
and worst case an upstream subscription will fly and it is fine.
Also avoid calling request upfront if we're on an unbounded subscription.
> Optimize MultiFilterOp on the hot path

- documentation/src/main/docs/faq.adoc
- documentation/src/main/docs/getting-started.adoc
- documentation/src/main/docs/index.adoc
- documentation/src/main/docs/intro.adoc
- documentation/src/main/docs/philosophy.adoc
I noticed a few typos in the doc while reading it.
> Fix documentation typos

- implementation/src/main/java/io/smallrye/mutiny/operators/UniSerializedSubscriber.java
This method isn't used anymore.
> Remove UniSerializedSubscriber isCancelledOrDone

- implementation/src/main/java/io/smallrye/mutiny/subscription/SwitchableSubscriptionSubscriber.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniRepeatTest.java
@jponge That fixes the issue you reported with UniRepeat.
> Fix potential deadlock in the SwitchableSubscriptionSubscriber

- implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java
When the Javadoc is read from an IDE, `until an subscriber subscribes` is shown.
> Fix UniCreate.deferred Javadoc

- implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
- implementation/src/main/java/io/smallrye/mutiny/operators/DefaultUniEmitter.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/BaseMultiEmitter.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/MultiEmitter.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/UniEmitter.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniCreateFromEmitterTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/EmitterBasedMultiTest.java
Fix #417
If the registration is done on a terminated (completed, failed, or canceled) emitter, the callback is invoked immediately.
> Handle late registration of onTermination callback

- implementation/src/main/java/io/smallrye/mutiny/converters/uni/ToPublisher.java
- implementation/src/main/java/io/smallrye/mutiny/converters/uni/UniToMultiPublisher.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/ParameterValidation.java
- implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
- implementation/src/main/java/io/smallrye/mutiny/operators/UniSerializedSubscriber.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFlatMapOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatUntilOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatWhilstOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/CollectionBasedMulti.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/ParameterValidationTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniCreateFromEmitterTest.java
A set of performance-oriented optimisations and cleanups.
> Internal optimisations

- .build/GitBlameDeprecated.java
- implementation/revapi.json
- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/Uni.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiSkip.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiReceiveItemOnTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniRunSubscriptionOnTest.java
- reactor/revapi.json
Remove subscribeOn method - deprecated since April 2020.
Also fix revapi configuration:
* missing root package in the `implementation` module
* limit the scope to the converter package in the `rxjava` and `reactor` modules
The first change requires adding a few justifications due to the addition of the `skip`, `select`, `collect` and `group` methods.
Also add the missing `comparator` parameter in javadoc in `multi.skip().repetition(Comparator)`
> remove subscribeOn and configure revapi properly

- implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
Iteration optimisations for Infrastructure#MULTI_INTERCEPTORS and UNI_INTERCEPTORS
This optimises the iteration of MULTI_INTERCEPTORS and UNI_INTERCEPTORS , with a focus on object allocations.
Should not introduce any semantic changes.
> Iteration optimisations regarding Infrastructure's interceptors

- implementation/src/main/java/io/smallrye/mutiny/groups/UniRepeat.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatUntilOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniRepeatTest.java
> Fix repetition when the first emitted item is `null`

- .build/WaitForCentral.java
> New script that waits until artifacts lands on a maven repo

- .github/workflows/deploy-site.yml
- .github/workflows/post-release.yml
- .github/workflows/prepare-release.yml
Fix #446
- The web site build will wait for the artifacts to land in Maven Central
- Prepare release would not push to master
- The justification clearing is postponed to the post-release workflow and is executed after the maven artifacts are made available in Maven Central
> Improve release process

- implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniMemoizeOp.java
- implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java
Fix #460
﻿Memoize needs to check for late subscribers after their subscription attempt.
> Fix memoize missing late subscriber subscription

- implementation/src/main/java/io/smallrye/mutiny/helpers/test/OnCancellationUniSignal.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/test/OnFailureUniSignal.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/test/OnItemUniSignal.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/test/OnSubscribeUniSignal.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriber.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/test/UniSignal.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriberTest.java
This is useful to check if a `Uni` has received signals in correct order.
> Uni signals tracking and ordering assertion in UniAssertSubscriber

- documentation/src/main/jekyll/_data/guides.yml
- documentation/src/main/jekyll/getting-started/transforming-items-async.adoc
- documentation/src/main/jekyll/guides/collecting-items.adoc
- documentation/src/main/jekyll/guides/combining-items.adoc
- documentation/src/main/jekyll/guides/completion-stages.adoc
- documentation/src/main/jekyll/guides/filter.adoc
- documentation/src/main/jekyll/guides/imperative-to-reactive.adoc
- documentation/src/main/jekyll/guides/merge-concat.adoc
- documentation/src/main/jekyll/guides/reactive-to-imperative.adoc
- documentation/src/main/jekyll/guides/repetitions.adoc
- documentation/src/main/jekyll/guides/rx.adoc
- documentation/src/main/jekyll/guides/take-skip.adoc
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
Here's another round of doc typos fixing.
> Fix doc typos

- implementation/src/main/java/io/smallrye/mutiny/Uni.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniReplaceWithTest.java
Uni.replaceWithNull is useful, but sometimes we need the return type to be switched to Void.
Fixes #486
> Uni.replaceWithVoid

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiGroupIntoLists.java
In the previous implementation the logic was partly handled by calling intoMultis().every(Duration). This was causing to get an unlimited number of items from upstream.
When processing a kafka stream with many small messages fitting in memory, the throttled policy would eventually (60seconds) see 'stale' non-processed messages causing an exception shutting processing down completely. This problem is solved using the MultiBufferWithTimeoutOp directly.
> keep pushback intact on Multi.groupItems().intoLists().of(size,duration)

- implementation/src/main/java/io/smallrye/mutiny/groups/UniRepeat.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatUntilOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatWhilstOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniRepeatTest.java
> Allow configuring a delay between two repetitions

- implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/test/AssertSubscriberTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiEmitOnTest.java
To work around the race condition, the awaitNextItem method handles the requests to attach the event listener before emitting the demands.
> Fix a request / consume race when using .request(x).awaitNextItems(x)

- implementation/pom.xml
Move it to the test scope, avoiding a hard runtime dependency.
> Break dependency to mutiny-test-utils

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/IntervalMulti.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/test/AssertSubscriberTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromTimePeriodTest.java
Delay the start of the ticks until we get the first initial request.
Related to https://github.com/smallrye/smallrye-reactive-messaging/issues/1125.
> Delay the start of the "ticks" after the first request.

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiMerge.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiMergeTest.java
Resolving #516:
- MultiMerge.streams now accepts Iterable<? extends Publisher<T>> instead of Iterable<Publisher<T>>
- MultiMergeTest now tests this behaviour
> #516 Let MultiMerge.streams accept Iterable<? extends Publisher<T>>

- implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriber.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/test/AssertSubscriberTest.java
The previous one has a race condition and so was missing events.
> New approach for the awaitItems method in the AssertSubscriber

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/CollectionBasedMulti.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromIterableTest.java
If the create multi get bounded requests and then an unbounded request, it restarts consuming the collection from the initial index, which is obviously wrong.
This PR skips the already sent items.
> Fix duplicate items issue when create a multi from a collection

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiLastItemOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiCollectTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiSelectFirstOrLast.java
The collect().last() operator was requesting Long.MAX but also propagating the requests from the downstream generating useless requests to the upstream.
> Multiple upstream requests in the multi.collect().last() operator

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiRetry.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniRetry.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniDelayOnItem.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniDelayUntil.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniOnFailureTransform.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromCompletionStageWithState.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromDeferredSupplierWithState.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromEmitterWithState.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromFailureSupplier.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromFuture.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromItemSupplier.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromItemWithState.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateWithEmitter.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/SneakyThrow.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromItemsTest.java
Under Java semantics it's not normally possible to throw a checked exception from some method that does not declare it, but using the infamous sneaky throw technique or languages like Kotlin this is totally doable.
This commit catches Throwable rather than RuntimeException in places where this may happen.
> Catch Throwable rather than RuntimeException

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiBufferWithTimeoutOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiCollectorOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiLastItemOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnItemInvoke.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOperatorProcessor.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSelectFirstWhileOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/overflow/MultiOnOverflowBufferOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromPublisher.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiCombineTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiGroupTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromResourceTest.java
In various place, we needed to keep a local reference, to avoid running into NPE.
> Release the downstream subscriber upon cancellation.

- math/src/main/java/io/smallrye/mutiny/math/MaxOperator.java
- math/src/test/java/io/smallrye/mutiny/math/AverageOperatorTest.java
- math/src/test/java/io/smallrye/mutiny/math/AverageOperatorWithDoubleTest.java
- math/src/test/java/io/smallrye/mutiny/math/AverageOperatorWithIntegerTest.java
- math/src/test/java/io/smallrye/mutiny/math/CountOperatorTest.java
- math/src/test/java/io/smallrye/mutiny/math/IndexOperatorTest.java
- math/src/test/java/io/smallrye/mutiny/math/MaxOperatorTest.java
- math/src/test/java/io/smallrye/mutiny/math/MedianOperatorTest.java
- math/src/test/java/io/smallrye/mutiny/math/MinOperatorTest.java
- math/src/test/java/io/smallrye/mutiny/math/StatisticOperatorTest.java
- math/src/test/java/io/smallrye/mutiny/math/SumOperatorTest.java
- math/src/test/java/io/smallrye/mutiny/math/TopOperatorTest.java
Rewrite some of the tests to avoid race conditions when waiting for items vs. terminal events. 
These tests are now repeated 1000 times.
> Fix race condition in test

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
JavaDoc for 
- `MultiOnItem.transformToUniAndConcatenate` and 
- `MultiOnItem.transformToUniAndMerge` 
seems to be accidentally swapped. This PR moves the JavaDoc to the right places.
> Move JavaDoc for MultiOnItem.transformToUniAndConcatenate

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSelectFirstOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiSelectFirstOrLastTest.java
Fix #605.
Keep a reference on the downstream so we can send the completion event after the cancellation
> Fix NPE happening after cancellation in MultiSelectFirstOp

- documentation/src/main/jekyll/_data/categories.yml
- documentation/src/main/jekyll/_data/guides.yml
- documentation/src/main/jekyll/guides/joining-unis.adoc
- documentation/src/test/java/guides/operators/UniJoinTest.java
- implementation/src/main/java/io/smallrye/mutiny/Uni.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniJoin.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinAll.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinFirst.java
- implementation/src/test/java/io/smallrye/mutiny/operators/uni/UniJoinTest.java
`Uni.join().{builder/all/first}` API.
It is simpler than `Uni.combine()`, and likely better matches what users do (e.g., passing a list of homogeneous operations).
There is no transformation API, `Uni.join().all(...)` emits a `List<T>` that can be subsequently processed with `Uni.onItem().{...}`.
> New Uni join API

- pom.xml
> Update Kotlin and Coroutines to 1.5

- kotlin/pom.xml
Hi. This minor change would be a great improvement for productization purposes. The problem with dokka plugin is that it does not work in the productization environment (Project Newcastle), so we need a way to turn it off.
Until now, productization engineers have been removing the plugin manually before each release. As part of streamlining and automating the build, it would be nice to have a way to simply turn it off from the command line.
Maybe there's a command line option to skip it, but I couldn't find it in the docs https://kotlin.github.io/dokka/1.4.32/user_guide/maven/usage/, so I suppose the best way to go forward would be to move the plugin into a profile that's active by default, so adding `-P!dokka` to the cmdline will skip it. WDYT?
> Move dokka plugin to its own profile to be able to skip it

- context-propagation/src/main/java/io/smallrye/mutiny/context/DefaultContextPropagationInterceptor.java
- context-propagation/src/main/java/io/smallrye/mutiny/context/MutinyContextManagerExtension.java
- context-propagation/src/test/java/io/smallrye/mutiny/context/MultiContextPropagationTest.java
- context-propagation/src/test/java/io/smallrye/mutiny/context/UniContextPropagationTest.java
This is required by https://github.com/quarkusio/quarkus/issues/18689
Fixes #626
> Use the thread-local ThreadContext in order to be able to define which contexts get propagated

- implementation/src/main/java/io/smallrye/mutiny/Uni.java
The documentation for the `Uni.map` method states `This method is equivalent to {@code uni.onItem().apply(x -> ...)}`. This is incorrect. It should be `This method is equivalent to {@code uni.onItem().transform(x -> ...)}`
> Documentation for Uni.map incorrect

- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniFailOnTimeout.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniOnCancellation.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniOnCancellationCall.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniOnFailureFlatMap.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniOnItemOrFailureFlatMap.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniOnItemTransformToUni.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniOperatorProcessor.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniRetryAtMost.java
- Avoid allocating excessive amounts of AtomicReference instances
- Improve abstraction over internal state of UniOperatorProcessor
- Use further atomic field updaters in selected places (Uni)
- Use CaS methods in UniOperatorProcessor
> Use atomic field updaters in selected Uni places

- implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
The `CallbackDecorator` provided by Contex Propagation has a strong impact on performance, and in some contexts unnecessary.
It's rather tricky to remove it from classpath, so it would be very handy to have a different option to disable it.
cc/ @jponge @FroMage
> Allow disabling all Callback decorators via environment properties

- implementation/src/main/java/io/smallrye/mutiny/groups/UniRepeat.java
Unless I misunderstood something, the Javadoc should contain this.
> Fix UniRepeat#until javadoc

- implementation/src/main/java/io/smallrye/mutiny/helpers/ExponentialBackoff.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryWhenTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureRetryTest.java
> Fix off-by-one retry count when using exponential backoff

- .github/workflows/build-main.yml
- .github/workflows/build-pull.yml
- .github/workflows/deploy-release.yml
- .github/workflows/deploy-site.yml
- .github/workflows/post-release.yml
- .github/workflows/prepare-release.yml
The caching uses actions/cache@v2 under-the-hood.
This reduces our YAML debt.
> Use the setup-java caching

- implementation/src/main/java/io/smallrye/mutiny/Uni.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniJoin.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/ParameterValidation.java
- implementation/src/test/java/io/smallrye/mutiny/operators/uni/UniJoinTest.java
> Check for emptiness when joining an empty set of Unis and extend Javadoc

- implementation/revapi.json
- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiIfNoItem.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItemTimeout.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFailOnItemTimeout.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiIfNoItemTest.java
This PR adds `ifNoItem()` to Multi allowing for handling when a stream is slower than expected. The operator uses a timer to count down the time since the last item was emitted and will throw a TimeoutException if the threshold is exceeded. This PR does not address the overall time it takes a Multi to terminate, only the time between items.
Usage:
- multi.ifNoItem().after(Duration.ofMillis(1000)).fail() // Propagate a TimeoutException
- multi.ifNoItem().after(Duration.ofMillis(1000)).recoverWithCompletion() // Complete the event on timeout
- multi.ifNoItem().after(Duration.ofMillis(1000)).on(myExecutor)... // Configure the executor calling on timeout actions
The code in this PR is largely copied from the Uni equivalent. Key differences are: 
- Operator resets the timer rather than closing …
> Add item timeouts to Multi

- documentation/src/main/jekyll/_layouts/index.html
The example that comes on this site: https://smallrye.io/smallrye-mutiny/ is not working as expected, because the method
`fail(Throwable failure)` was replaced by `failWith(Throwable failure)`. Also `.subscribe().with` doesn't return a `Uni`. 
If you think that the proposed changes are too "verbose" could be summarized into 
```
Uni&lt;String&gt; request = (...)
request.ifNoItem().after(ofMillis(100)).failWith(new Exception("💥"))
.onFailure().recoverWithItem(fail -> "📦")
.subscribe()
.with(item -> log("👍 " + item));
```
But I try to keep the same amount of lines as the current implementation.
> Update documentation example

- implementation/pom.xml
This saves a few minutes while iterating on the Mutiny code base.
> Maven profile to skip running the Reactive Streams TCK tests

- pom.xml
Bundles https://github.com/smallrye/smallrye-mutiny/pull/753 and https://github.com/smallrye/smallrye-mutiny/pull/765
> Update Kotlin and Dokka to 1.6.0

- implementation/src/test/java/io/smallrye/mutiny/groups/MultiDisjointTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromTimePeriodTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiEmitOnTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiIfNoItemTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureInvokeTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnItemFailWithTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnSubscribeTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniIfNoItemTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureTransformTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureInvokeTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureMapTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOrTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniRunSubscriptionOnTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniSubscribeAsCompletionStageTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniToPublisherTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/processors/UnicastProcessorTest.java
- implementation/src/test/java/io/smallrye/mutiny/subscription/SerializedSubscriberTest.java
- implementation/src/test/java/io/smallrye/mutiny/unchecked/UncheckedConsumerTest.java
- implementation/src/test/java/junit5/support/AwaitilityConfigurationExtension.java
- implementation/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
- implementation/src/test/resources/junit-platform.properties
Work to reduce flakiness of the tests suite.
> Reduce tests flakiness, especially in CI / constrained environments

- implementation/src/main/module/module-info.java
- math/src/main/module/module-info.java
There is little benefit from strong encapsulation at this stage.
Fixes #739
> Rework the module-info declarations to be fully open modules

- kotlin/pom.xml
Tracked by https://github.com/Kotlin/dokka/issues/2163
> Reactivate dokka for all JDK versions

- kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Multi.kt
- kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Uni.kt
- kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/DeferredAsUniTest.kt
- kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/FlowAsMultiTest.kt
- kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/MultiAsFlowTest.kt
- kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/TestUtil.kt
- kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/UniAwaitSuspendingTest.kt
- pom.xml
*  Refactored and cleaned up tests.
* Update Coroutines to 1.6
* Needed to increase language/api version to 1.5 because of method signature changes in `Flow` that are only supported from 1.5 onwards (causing the test failures of https://github.com/smallrye/smallrye-mutiny/pull/788)
> Update Coroutines to 1.6.0, Kotlin API to 1.5 and refactored tests

- context-propagation/pom.xml
- documentation/src/main/jekyll/_data/versions.yml
- pom.xml
- reactive-streams-junit5-tck/README.md
- reactive-streams-junit5-tck/pom.xml
- reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/IdentityProcessorVerification.java
- reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/NotVerifiedException.java
- reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/PublisherVerification.java
- reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/SubscriberBlackboxVerification.java
- reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/SubscriberWhiteboxVerification.java
- reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/TestngSkippingExtension.java
- reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/TestngSkippingExtensionTest.java
- Revert "Bumping the website version to 1.3.0"
- Revert "Pin the removed JUnit5 RS TCK to 1.2.0"
- Bring back the JUnit5 RS TCK shim
> Bring back the JUnit5 RS TCK shim

- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroupIterable.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniAndCombination.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniZipTest.java
Note: `Uni.combine().any()` must not support concurrent limits, because the semantic is to forward the result of the fastest `Uni` (item or failure).
> Limit concurrency in Uni.combine().all()

- implementation/src/main/java/io/smallrye/mutiny/groups/UniJoin.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinAll.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinFirst.java
- implementation/src/test/java/io/smallrye/mutiny/operators/uni/UniJoinTest.java
Also removed dropped exception logging, cancellation on a join effectively means that failures shall be discarded.
> Avoid `Uni.join().first(unis).toTerminate()` with a concurrency limit

- implementation/revapi.json
- implementation/src/main/module/module-info.java
We incorrectly assumed that open modules would export all packages, which is not the case.
- Open modules allow for (deep) reflection to all classes, which is something we want to allow. We have no good reason right now to restrict reflection in Mutiny.
- Exported packages need to be added manually, there is no wildcard. I did a selection of packages that shall be in the public API.
- I fixed transitive 'requires' clauses: Reactive Streams is part of the Mutiny API, just like SmallRye Common Annotations.
> JPMS open modules do not export packages

- implementation/src/main/java/io/smallrye/mutiny/groups/UniMemoize.java
- implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java
> Avoid overflow when using ChronoUnit.FOREVER with the memoize operator

- documentation/src/main/jekyll/getting-started/creating-multis.adoc
- documentation/src/test/java/guides/CreatingMultiTest.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiReplay.java
> Document creating Multis from a generator

- implementation/revapi.json
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiReplay.java
> Add the missing CheckReturnValue annotations to the Multi replay operator API

- documentation/src/main/jekyll/_data/categories.yml
- documentation/src/main/jekyll/_data/guides.yml
- documentation/src/main/jekyll/guides/controlling-demand.adoc
- documentation/src/test/java/guides/operators/ControlDemandTest.java
- implementation/revapi.json
- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiDemandPacing.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiDemandPacer.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/DemandPacer.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/FixedDemandPacer.java
- implementation/src/test/java/io/smallrye/mutiny/groups/MultiDemandPacingTest.java
- implementation/src/test/java/io/smallrye/mutiny/subscription/DemandPacerRequestTest.java
Demand pacing can be controlled from previous demands and the number of emitted items since the last request.
The initial implementation ships with a fixed demand implementation of the demand pacing interface.
Users can easily define their own policies, and we can introduce other concrete implementations in the future given use-cases and patterns.
This operator is not reactive-streams compliant because the downstream demand has to be ignored.
See #872
> New Multi demand pacing operator

- .build/BlameAPI.java
- Typo in the CLI documentation
- BlameAPI would catch itself for deprecation search
> Misc fixes to .build/BlameAPI.java

- documentation/src/main/jekyll/guides/controlling-demand.adoc
- documentation/src/test/java/guides/operators/ControlDemandTest.java
- implementation/revapi.json
- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiDemandCapping.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiDemandCappingTest.java
- reactive-streams-tck-tests/src/test/java/io/smallrye/mutiny/tcktests/MultiDemandCappingTckTest.java
> New experimental demand capping operators

- implementation/pom.xml
- implementation/revapi.json
- implementation/src/main/module/module-info.java
This API was documented, so it shall be JPMS-enabled.
Fixes #881
> Move io.smallrye.mutiny.operators.multi.processors to the public API

- documentation/src/main/jekyll/guides/controlling-demand.adoc
- documentation/src/test/java/guides/operators/ControlDemandTest.java
- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiDemandCapping.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiDemandCappingTest.java
Although not apparent in the TCK tests, not tracking the outstanding demand is against the RS semantics.
This changes the capping evaluation from that of the triggering (subscription) request to evaluating the outstanding demand.
Fixes #886
> Fix the capping operators outstanding demand management

- documentation/src/main/jekyll/guides/shortcuts.adoc
The generated documentation for uni.eventually was missing the parenthesis.
Now it is correctly showing
`
uni.eventually(() → System.out.println("eventually"))
`
instead of
`
uni.eventually) → System.out.println("eventually"
`
and
`
uni.onItemOrFailure().invoke((ignoredItem, ignoredException) → System.out.println("eventually"))
`
instead of
`
uni.onItemOrFailure().invokeignoredItem, ignoredException) → System.out.println("eventually"
`
in the documentation.
> Update shortcuts.adoc to show the parenthesis of the uni.eventually shortcut

- implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
This is part of a larger bug fix in Quarkus, see https://github.com/quarkusio/quarkus/issues/25818
> Avoid wrapping scheduled executors

- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiFlatten.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiConcatMapOp.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/SwitchableSubscriptionSubscriber.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnItemFailWithTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToUniTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiConcatMapNoPrefetchTest.java
- reactive-streams-tck-tests/src/test/java/io/smallrye/mutiny/tcktests/MultiConcatMapNoPrefetchCompletionStageTckTest.java
- reactive-streams-tck-tests/src/test/java/io/smallrye/mutiny/tcktests/MultiConcatMapNoPrefetchTckTest.java
Requests are forwarded lazily to the upstream when:
* First downstream request
* The inner has no more outstanding requests
* The inner completed without emitting items or with outstanding requests
Added entrypoints `Multi.concatMap(mapper, prefetch)` and `MultiFlatten.concatanate(prefetch)`.
Existing `transformTo[Uni|Multi]AndConcatanate` methods default to `prefetch=true` for backwards compatible behavior.
Typically this operator allows applying async transformation on each item of a Multi, without prefetching an additional item from the upstream.
> ConcatMap operator without prefetch

- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiFlatten.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiConcatMapOp.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/SwitchableSubscriptionSubscriber.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiConcatMapNoPrefetchTest.java
- pom.xml
- reactive-streams-tck-tests/src/test/java/io/smallrye/mutiny/tcktests/MultiConcatMapNoPrefetchCompletionStageTckTest.java
- reactive-streams-tck-tests/src/test/java/io/smallrye/mutiny/tcktests/MultiConcatMapNoPrefetchTckTest.java
Backport of #997 to 1.x branch.
ConcatMap methods default to the previous implementation of prefetching.
> Concatmap no prefetch – backport 1.x

- pom.xml
Reverts smallrye/smallrye-mutiny#1015 - this version of TestNG needs Java 11.
> Revert "Bump testng from 7.5 to 7.6.1"

- reactive-streams-operators/pom.xml
This requires downgrading Maven Surefire for the reactive-streams-operators module as otherwise the TestNG test from the TCK fails to be instantiated.
> Run the Reactive Streams Operators TCK again

- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/Uni.java
> Fix description of some operator shortcuts in Javadoc

- implementation/src/main/java/io/smallrye/mutiny/helpers/UniCallbackSubscriber.java
The bytecode of the original `UniCallbackSubscriber::onItem` method reports:
```java
// access flags 0x11
// signature (TT;)V
// declaration: void onItem(T)
public final onItem(Ljava/lang/Object;)V
TRYCATCHBLOCK L0 L1 L2 java/lang/Throwable
L3
LINENUMBER 70 L3
GETSTATIC io/smallrye/mutiny/helpers/UniCallbackSubscriber.SUBSCRIPTION_UPDATER : Ljava/util/concurrent/atomic/AtomicReferenceFieldUpdater;
ALOAD 0
GETSTATIC io/smallrye/mutiny/helpers/EmptyUniSubscription.CANCELLED : Lio/smallrye/mutiny/subscription/UniSubscription;
INVOKEVIRTUAL java/util/concurrent/atomic/AtomicReferenceFieldUpdater.getAndSet (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
CHECKCAST org/reactivestreams/Subscription
ASTORE 2
L4
LINENUMBER 71 L4
ALOAD 2
GETSTATIC …
```
> Hidden Subscription checkcast scalability issue (Fixes #1080)

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOverflow.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOverflowStrategy.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/UniCallbackSubscriber.java
- implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
- implementation/src/test/java/io/smallrye/mutiny/infrastructure/InfrastructureTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnOverflowTest.java
- Fixed `multi.onOverflow().buffer()` to use an infrastructure-provided default buffer size
- Added `multi.onOverflow().bufferUnconditionally()` as an unbounded strategy
- Fixed the documentation
- Added a few tests
Fixes #1040
> Multi overflow unbounded strategy was actually bounded

- implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/BlockingIterableTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromTimePeriodTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiIfNoItemTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToMultiTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniAwaitTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniIfNoItemTest.java
- implementation/src/test/java/junit5/support/AwaitilityConfigurationExtension.java
- pom.xml
- GitHub Action expose a `CI=true` environment variable
- A few JUnit tests had useless hard-coded timeouts
-  Some long running tests have seen explicit timeouts increased to accomodate slow runners
Note: this has been tested across multiple runs in a tiny sized QEmu Linux VM.
> Reduce flaky tests by increasing timeouts in CI

- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniOperatorProcessor.java
Fixes #1112
The problem with the type checks was in the implied check on the return type compatibility of the `ParameterValidation.nonNull` method: it being generic, a check is necessary - normally this would be extremely cheap and negligible but in this case we better avoid assigning the returned reference.
cc/ @jponge
> Avoid type cache pollution on parameter validation in UniOperatorProcessor

- implementation/src/main/java/io/smallrye/mutiny/groups/UniCombine.java
Remove the duplicated "a failure" in "... fires an item or a failure a failure, ...".
> Fix typo in Javadoc of UniCombine.any()

- documentation/docs/guides/merging-and-concatenating-streams.md
Just by looking both diagrams I was confused to find what was the difference. I think it can be more clear by naming the "Merged Stream" the "Concatenated Stream" in case of Concatenation what seems to be confirmed by the text just after the second diagram "the concatenated stream sends the completion event."
> Replace "Merged Stream" by "Concatenated Stream"

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromPublisherTest.java
This optimization avoids rewrapping the Multi, using a wrapper subscriber, and skipping the onMultiCreation callback.
> When using Multi.createFrom().publisher and Multi.createFrom().safePublisher, return that Multi

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromPublisherTest.java
This optimization avoids rewrapping the Multi, using wrapped subscribers and also skips `onMultiCreation` callback.
(cherry picked from commit 699ae6e19bf0668621a5425c2261cfc0ecdbfdd4)
> When using `Multi.createFrom().publisher` and `Multi.createFrom().safePublisher` with a Multi, return that Multi directly

- implementation/src/main/java/io/smallrye/mutiny/Uni.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
Fixes #1181
See https://github.com/hibernate/hibernate-reactive/issues/1436
> Ensure Uni.eventually() also handles cancellation signals

- documentation/docs/guides/shortcut-methods.md
- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/Uni.java
- implementation/src/main/java/io/smallrye/mutiny/groups/GeneratorEmitter.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnFailure.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnRequest.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnTerminate.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniMemoize.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailure.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniOnSubscribe.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/StrictMultiSubscriber.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/queues/Queues.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/spies/Spy.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiConcatMapOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiScanOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSkipFirstOp.java
- implementation/src/main/java/io/smallrye/mutiny/subscription/SafeSubscriber.java
- implementation/src/test/java/io/smallrye/mutiny/converters/UniCreateFromTest.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/test/AbstractSubscriberTest.java
- implementation/src/test/java/io/smallrye/mutiny/helpers/test/AssertSubscriberTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiGroupTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiSkipTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniAwaitTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemFailWithTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniZipTest.java
- implementation/src/test/java/io/smallrye/mutiny/unchecked/UncheckedFunctionTest.java
Fix #1224
- Remove then from the shortcut list and from the javadoc
- Apply the new formatter.
> Remove reference to the `then` shortcut

- pom.xml
failSeverity is deprecated and replaced with maximumCriticality.
However, renaming the XML tag results in an obscure error due to a conflict with the JSON settings. Removing that XML configuration fragments solves the issue.
Note: I have tested locally renaming a method in the public API and it got properly reported as breaking change.
> Remove failSeverity RevAPI XML configuration

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSubscribeOnOp.java
- Reuse more of the super class defaults
- Account for later cancellation
> Simplify the MultiSubscribe operator implementation

- implementation/revapi.json
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiGroupIntoLists.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiBufferWithTimeoutOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiGroupTest.java
Emit empty lists in the MultiBufferWithTimeoutOp operator when no items have been emitted during the time window.
Also fix the javadoc, as this was the described behavior.
> Emit empty list when grouping item by time windows and no item in the window

- implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiConcatMapNoPrefetchTest.java
This is to reduce CI failures due to this flaky test for which investigations are under way.
See: https://github.com/smallrye/smallrye-mutiny/issues/1254
> Disabling MultiConcatMapNoPrefetchTest in CI until 1254 has been fixed

- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniMemoizeOp.java
- implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java
Moving to a lock-based design with a 3 states machine. This is more appropriate to the requirements of memoization wrt signals.
Fixes #1303
> Fix race conditions un UniMemoizeOp

- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniMemoizeOp.java
- implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java
The subscription event was sent after the item or failure in most cases, which was wrong.
> Fix the protocol in Uni memoization

- kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Multi.kt
- kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Uni.kt
- kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/MultiAsFlowTest.kt
- kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/UniCoroutineBuilderTest.kt
Tries to solve https://github.com/smallrye/smallrye-mutiny/issues/1316
Fixes https://github.com/smallrye/smallrye-mutiny/issues/1324
@hantsy, you're right, the `suspend` modifier is not needed for `asFlow`.
Your referenced implementation of kotlinx-coroutines-reactive would required an additional dependency, that's why I would prefer to stay with the own implementation, especially as it's also capable of buffer handling.
> Issue #1316: Kotlin - Remove unnecessary suspend modifier from asFlow and Uni builder

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiConcatMapOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiConcatMapNoPrefetchTest.java
Change how the upstream request is deferred until the next downstream request
> Fix concat map request race condition which resulted in flaky test

- .build/WaitForCentral.java
- context-propagation/src/test/java/io/smallrye/mutiny/context/UniContextPropagationTest.java
- documentation/src/test/java/guides/operators/CombiningItemsTest.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup2.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup3.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup4.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup5.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup6.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup7.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup8.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup9.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroupIterable.java
- implementation/src/test/java/io/smallrye/mutiny/infrastructure/MutinySchedulerTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniAndTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniZipTest.java
- Replaces combinedWith by with((a,b,c) -> d).
- Introduces withUni((a,b,c) -> Uni).
> refactor: reworked Uni combination APIs

- workshop-examples/src/main/java/_07_advanced_streaming/_01_Multi_Split.java
- workshop-examples/src/main/java/_08_misc/_01_Multi_Custom_Operator.java
- workshop-examples/src/main/java/_08_misc/_02_Logging.java
- workshop-examples/src/main/java/_08_misc/_03_Context.java
> docs: add a workshop example for Multi::split

- documentation/docs/guides/branching.md
- documentation/mkdocs.yml
- documentation/src/test/java/guides/BranchingTest.java
- workshop-examples/src/main/java/_03_composition_transformation/_20_Uni_Branching.java
- workshop-examples/src/main/java/_03_composition_transformation/_21_Multi_Branching.java
> docs: document how to express branching in a pipeline

- .build/justfile-for-release
- .github/workflows/build-main.yml
- .github/workflows/push-release-to-maven-central.yml
- pom.xml
A few fixes based on observations of what worked, what didn't, and what can be improved.
We're essentially back to a separate workflow to deploy to Maven Central, given how unreliable the gateway can be.
The deployment of 2.5.0-M1 had failed in CI on the Maven side due to a gateway error, but the artifacts actually made it to Maven Central.
> Release CI enhancements after 2.5.0-M1

- .build/justfile-for-release
- .github/workflows/push-release-to-maven-central.yml
- .github/workflows/release.yml
- Typo in a workflow step
- Delay git push
- Ensure JReleaser has a reference to the previous release
> CI Fixes after 2.5.0-M2

- implementation/pom.xml
- math/pom.xml
- pom.xml
This relocation had gone un-noticed, causing Mutiny to use an older Jandex.
> build(maven): use the Jandex Maven plugin from SmallRye rather than JBoss

- implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
This changes the AssertSubscriber items list back tyo CopyOnWriteArrayList. 
The synchronized list is not very practical to write assertions with concurrent access to the list. It requires that the list access is also synchronized on the list.
> Change the AssertSubscriber items list back to copyOnWrite

- pom.xml
Replaces
* https://github.com/smallrye/smallrye-mutiny/pull/1395
* https://github.com/smallrye/smallrye-mutiny/pull/1399
Kotlin 1.9.10 and coroutine 1.7.3 is also used in Quarkus BOM, so no compatibility issues should occur.
> build(deps): bump kotlin to 1.9.10 and dokka to 1.9.0

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiBufferWithTimeoutOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiDemandPacer.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiWindowOnDurationOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/multicast/MultiReferenceCount.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniDelayOnItem.java
- implementation/src/test/java/io/smallrye/mutiny/groups/UniOnFailureRetryTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiIgnoreTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniCreateFromFutureTest.java
This causes spurious interrupt signals in failure retry with exponential backoff that get propagated downstream.
Also https://twitter.com/relizarov/status/1184460504238100480
Fixes #1436
> fix: do not interrupt threads on cancellation in UniDelayOnItem

- documentation/docs/tutorials/retrying.md
- implementation/src/main/java/io/smallrye/mutiny/groups/UniRetry.java
Happened as discussed here; https://github.com/smallrye/smallrye-mutiny/discussions/1427
> docs: make clearer that retry until/when does not support backoff

- implementation/src/main/java/io/smallrye/mutiny/Uni.java
from().value() does not exist.
> docs: fix javadoc for deferred uni creation

- implementation/revapi.json
- implementation/src/main/java/io/smallrye/mutiny/helpers/Subscriptions.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiConcatMapOp.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiConcatOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiConcatMapNoPrefetchTest.java
This fixes race conditions in concatMap and stream concatenation operators.
Refs: #1388
> fix: rewrite of the concatenation operators

- implementation/src/test/java/io/smallrye/mutiny/operators/MultiConcatTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiConcatMapNoPrefetchTest.java
> test: increase the concatMap operator coverage

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiConcatMapOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiConcatMapNoPrefetchTest.java
Reverts b552fc4f, we will eventually need to come back to rewriting this operator.
> revert: rewrite of the concatenation operators

- kotlin/pom.xml
This fixes a compilation failure when upgrading to version 3.12.0
of the maven-compiler-plugin.
Fixes #1470
> fix: disable the Maven compiler plugin in the Kotlin module

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/replay/AppendOnlyReplayList.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/replay/ReplayOperator.java
- implementation/src/test/java/io/smallrye/mutiny/groups/MultiReplayTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/replay/ReplayOperatorTest.java
Fixes a memory leak caused by old subscriptions not being removed properly. In addition, this fixes the edge case where no completion event would be sent for replay subscriptions if the number of requested items was exactly equal to the number of available items.
Fixes #1482
> fix: properly remove subscriptions in ReplayOperator

- implementation/revapi.json
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiConcatMapOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiConcatMapNoPrefetchTest.java
In this implementation the operator acts as a simple no-queue forwarder
between the subscriber and the current upstream.
There is also a small dose of fine-grained locking around a few
state machine updates that can’t be expressed as non-blocking / compare & swap
operations.
> fix: rewrite the concatMap operator

- implementation/src/main/java/io/smallrye/mutiny/helpers/UniCallbackSubscriber.java
- implementation/src/test/java/io/smallrye/mutiny/groups/UniSubscriberTest.java
> fix: race condition on cancellation in UniCallbackSubscriber

- implementation/src/main/java/io/smallrye/mutiny/groups/MultiRetry.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniRetry.java
- implementation/src/main/java/io/smallrye/mutiny/helpers/ExponentialBackoff.java
- implementation/src/test/java/io/smallrye/mutiny/groups/UniOnFailureRetryTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryUntilTest.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureRetryUntilTest.java
> feat: allow failure retries with exponential backoffs and 'until' predicates

- documentation/docs/reference/going-reactive-a-few-pitfalls.md
- documentation/mkdocs.yml
- documentation/src/test/java/guides/reference/PitfallsTest.java
This reference page is to be completed with our observations of how users might have incorrect assumptions on how to use Mutiny and reactive in general.
> docs: addition of a reactive pitfalls reference

- workshop-examples/src/main/java/_03_composition_transformation/_22_Multi_Chunks_To_Sentence_Stream.java
- workshop-examples/src/main/java/_03_composition_transformation/_22_Multi_Chunks_To_Sentence_Stream_Custom_Operator.java
Two variants for the same example:
- concat map
- custom operator to capture required state
> docs: text chunks stream to sentence stream examples

- implementation/src/main/java/io/smallrye/mutiny/helpers/queues/Queues.java
- pom.xml
These do not require Unsafe access and make native compilation a non-issue.
> feat: upgrade to JCTools 4.0.4 and use atomic+unpadded queues

- .github/workflows/build-pull.yml
The reason is that dependabot easily creates long commit lines due to the artifact names, breaking rules.
Inspired by https://github.com/felipecrs/bindl/commit/f7de680e7bf39dde5e524dca0a0a13deb4c32574
> fix(ci): do not check conventional commits with dependabot

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnSubscribeCall.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnSubscribeTest.java
> fix: timing issue in MultiOnSubscribeCall where the Multi could terminate before the Uni

- RELEASING.md
- justfile
- pom.xml
- **docs: document on releasing Mutiny**
- **build: minor jreleaser-related cosmetic fixes**
> Minor JReleaser tweaks and documentation

- documentation/docs/guides/eliminate-duplicates-and-repetitions.md
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiSelect.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiDistinctByKeyOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiDistinctTest.java
- reactive-streams-tck-tests/src/test/java/io/smallrye/mutiny/tcktests/MultiSelectDistinctByKeyTckTest.java
As discussed in https://github.com/smallrye/smallrye-mutiny/discussions/1729, this PR adds an overload to `distinct` in `MultiSelect` so that a function can be provided to extract a key which is used to eliminate duplicates. This can provide a lower memory footprint than the 2 existing methods as only references to simpler key objects need to be kept rather than the objects themselves. An typical usage would be for cases the stream consists of large, complex objects but where a integer id can be used to identify duplicates.
This PR adds a new `AbstractMultiOperator` - `MultiDistinctByKeyOp` which is more or less the same as `MultiDistinctOp` with the addition of the extractor function and removal of the comparator. I think it would be possible to combine these classes, but as there is an …
> Additional overload of distinct using a key extractor

- implementation/revapi.json
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup2.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup3.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup4.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup5.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup6.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup7.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup8.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup9.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniZipTest.java
As discussed in #1735, this PR adds method overriding of the `usingConcurrencyOf(int)` to the classes `UniAndGroup2` , `UniAndGroup3`, `UniAndGroup4` and similar classes. 
Currently, `usingConcurrencyOf(int)` is implemented only in their common parent class `UniAndGroupIterable` which return an `UniAndGroupIterable` object, resulting in a loss of type information.
For example:
```java
public Uni<Integer> sumFromUnis() {
Uni<String> a = Uni.createFrom().item("1");
Uni<Integer> b = Uni.createFrom().item(2);
Uni<Float> c = Uni.createFrom().item(3.141);
return Uni.combine().all().unis(a, b, c)
.usingConcurrencyOf(1)
.with(l -> Integer.parseInt((String) l.get(0)) + (Integer) l.get(1) + Math.round((Float) l.get(2));
}
```
In this example, we must use `.with(List<T1>)` of `UniAndGroupIterable` …
> feat: improve type safety when combining unis with limited concurrency

- documentation/docs/guides/shortcut-methods.md
- implementation/src/main/java/io/smallrye/mutiny/Uni.java
The Uni::eventually(Runnable) operator had been previously moved from onItemOrFailure() to onTermination() semantics so as to handle cancellation on top of already handling items and failures.
This aligns the `eventually(Supplier<Uni<T>>)` variant with its `eventually(Runnable)` counterpart.
Fixes #1742.
BREAKING CHANGE: this may break code bases where onItemOrFailure() semantics were correctly assumed and cancellation was handled separately.
> Align the Uni::eventually operators to onTermination() semantics

- implementation/revapi.json
- implementation/src/main/java/io/smallrye/mutiny/Multi.java
- implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiEmitOnOp.java
- implementation/src/test/java/io/smallrye/mutiny/operators/MultiEmitOnTest.java
The operator was previously using a hard-coded buffer size of 16 elements which was also used to batch upstream demand.
This was a performance bottleneck for large streams as observed in the field.
The existing Multi::emitOn(executor) method remains, but it now uses Infrastructure.getBufferSizeS() as a default buffer size instead of 16.
We do not expect existing usages of emitOn(executor) to be affected by this internal change.
Fixes: #1758
See-Also: https://github.com/quarkusio/quarkus/issues/36177
> feat(operators)!: introduce a buffer size parameter to Multi::emitOn

- context-propagation/pom.xml
> fix: add an automatic module name to mutiny-smallrye-context-propagation

- implementation/src/main/java/io/smallrye/mutiny/Uni.java
- implementation/src/main/java/io/smallrye/mutiny/groups/UniIfNoItem.java
This pull request focuses on enhancing the documentation of the `after()` method within the `ifNoItem` chain in the `Uni` class, as well as correcting the return type documentation in the `UniIfNoItem` class. The changes are aimed at improving code 
readability and ensuring that the API documentation accurately reflects the expected behavior.
**Changes Made:**
1. **Improved Javadoc Formatting in `Uni.java`:**
- Updated the examples provided for the `after()` method from using `<code>` tags to a more readable format using `<pre>` with `@code`.
- This change enhances the clarity of the documentation, making it easier for developers to understand how to use the method effectively.
2. **Corrected Return Type in `UniIfNoItem.java`:**
- Fixed the Javadoc comment for the `after()` method to …
> Fix javadoc for ifNoItem method

- documentation/mkdocs.yml
See https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#stay-on-the-same-page-when-switching-versions
Note that this won't fix older published releases.
> docs: stay on the same page when switching website versions

- implementation/src/main/java/io/smallrye/mutiny/groups/Gatherer.java
- implementation/src/main/java/io/smallrye/mutiny/groups/Gatherers.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
- implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItemGather.java
- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiGather.java
- implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiGatherTest.java
- pom.xml
- reactive-streams-tck-tests/src/test/java/io/smallrye/mutiny/tcktests/MultiGatherTckTest.java
- workshop-examples/src/main/java/_03_composition_transformation/_22_Multi_Chunks_To_Sentence_Gather.java
The goal is to support cases where:
- the upstreams sends data in chunks
- chunks need to be assembled
- downstream items are extracted from the intermediary assembled chunks.
Examples include string chunks, network buffers, etc.
Fixes: #1597
> feat: introduction of a Multi gathering operator

- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniOnTermination.java
- implementation/src/test/java/io/smallrye/mutiny/operators/UniOnTerminationTest.java
This aligns with the other termination operators where the cancellation signal is sent upstream only after the callback / uni provider has completed.
Fixes #1843
> fix: harmonize cancellation and termination callback orders

- documentation/pom.xml
- implementation/pom.xml
- pom.xml
- test-utils/pom.xml
This ensures proper support for Java 24 and beyond, ahead of further restrictions on agent loading in future Java releases.
> build: explicit JVM settings for Jacoco and Mockito agents

- pom.xml
Fixes a potential issue for pushing to Maven Central and the new process.
See: https://github.com/camel-tooling/camel-language-server/commit/173be5f1b7a471865fcc39f758161ac197368f6f
> fix(build): skip cyclonedx-maven-plugin when not deploying

- implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiCombineLatestOp.java
- implementation/src/test/java/io/smallrye/mutiny/BugReproducersTest.java
A race condition existed due to double-stacking in a queue.
Fixes: #1891
> fix: race condition in MultiCombineLatestOp

- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniMemoizeOp.java
- implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java
There was a possibility for pipelines having multiple memoized Unis to cause a deadlock. This is due to the usage of an internal reeentrant lock that was held even when forwarding upstream and downstream signals, which is bad because this exposes to deadlocks by design, and this may also involved I/O operations.
Lock access has been rewritten to focus on short, purely state-affecting critical sections, and signals forwarding happens in a looser fashion.
Note that there is still a cancel() signal that can be forwarded under lock, but this should be a non-blocking operation as per Reactive Streams semantics and it shouldn't cause any other signal to back-propagate and deadlock.
Fixes: #1910
> fix: deadlock in Uni memoization

- pom.xml
Version 1.19.0 has a weird bug with BouncyCastle dependencies which I am going to report.
> build(deps): downgrade to JReleaser 1.18.0

- context-propagation/src/test/java/io/smallrye/mutiny/context/UniContextPropagationTest.java
- implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniMemoizeOp.java
- implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java
Spotted with a flaky test in UniContextPropagationTest and CI conditions.
> fix: race condition in UniMemoizeOp on awaiters forwarding
